try:
    pass
    try:
        pass
    except:
        pass
except Exception as e:
    print(e)
else:
    pass
finally:
    print('End')